// <auto-generated />
using System;
using FutbolLigi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FutbolLigi.Migrations
{
    [DbContext(typeof(FutbolLigiContext))]
    partial class FutbolLigiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FutbolLigi.Models.PuanTablosu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AtilanGol")
                        .HasColumnType("int");

                    b.Property<int?>("Beraberlik")
                        .HasColumnType("int");

                    b.Property<int?>("Galibiyet")
                        .HasColumnType("int");

                    b.Property<int?>("Maglubiyet")
                        .HasColumnType("int");

                    b.Property<string>("TakimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YenilenGol")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PuanTablosu");
                });
#pragma warning restore 612, 618
        }
    }
}
